version: '3.8'

services:
  # API Flask
  flask_app:
    build: .
    container_name: talentupq_flask
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    networks:
      - talentupq_network
    restart: unless-stopped
    volumes:
      - uploads_data:/app/static/uploads
      # Este volumen guarda tu base de datos SQLite para que no se borre
      - sqlite_data:/data

  # Cliente React
  react_app:
    build: ./frontend-react
    container_name: talentupq_react
    ports:
      - "3000:3000"
    networks:
      - talentupq_network
    restart: unless-stopped

volumes:
  uploads_data:
  sqlite_data:

networks:
  talentupq_network:
    driver: bridge